// One-off dev seeding script — creates 7 test vendors across Venue, Catering,
// and Photography with deliberately spread price ranges (budget/mid/luxury)
// so budget-based AI matching can be exercised manually in the app.
// Usage: node scripts/seedTestVendors.js
require('dotenv').config();
const bcrypt = require('bcrypt');
const sequelize = require('../db/sequelize');
const User = require('../db/models/user');
const Vendor = require('../db/models/vendor');
const VendorService = require('../db/models/vendorService');

const TEST_PASSWORD = 'VendorTest123!';

const VENDORS = [
  {
    email: 'contact@greenacresgardens.test',
    business_name: 'Green Acres Gardens',
    category: 'Venue',
    description: 'Relaxed outdoor garden venue with tented seating and a natural backdrop.',
    style_tags: ['Rustic', 'Bohemian'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 8000,
    price_max: 15000,
    unit: 'package',
  },
  {
    email: 'events@thepearlballroom.test',
    business_name: 'The Pearl Ballroom',
    category: 'Venue',
    description: 'Indoor ballroom venue with in-house décor team and a 300-guest capacity.',
    style_tags: ['Elegant', 'Modern'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 25000,
    price_max: 40000,
    unit: 'package',
  },
  {
    email: 'bookings@royalmanorestate.test',
    business_name: 'Royal Manor Estate',
    category: 'Venue',
    description: 'Luxury countryside estate offering a full weekend wedding experience.',
    style_tags: ['Elegant', 'Traditional'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 60000,
    price_max: 120000,
    unit: 'package',
  },
  {
    email: 'hello@mamaskitchencatering.test',
    business_name: "Mama's Kitchen Catering",
    category: 'Catering',
    description: 'Home-style Zambian catering, buffet service for up to 200 guests.',
    style_tags: ['Traditional'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 5000,
    price_max: 9000,
    unit: 'per event',
  },
  {
    email: 'info@signaturefeastcatering.test',
    business_name: 'Signature Feast Catering',
    category: 'Catering',
    description: 'Plated fine-dining catering with a customisable premium menu.',
    style_tags: ['Elegant', 'Modern'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 20000,
    price_max: 35000,
    unit: 'per event',
  },
  {
    email: 'studio@lensandlight.test',
    business_name: 'Lens & Light Studios',
    category: 'Photography',
    description: 'Clean, modern wedding photography with a same-week digital gallery.',
    style_tags: ['Modern', 'Minimalist'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 3000,
    price_max: 6000,
    unit: 'package',
  },
  {
    email: 'book@goldenhourphotography.test',
    business_name: 'Golden Hour Photography',
    category: 'Photography',
    description: 'Full-day premium coverage with a second shooter and a printed album.',
    style_tags: ['Elegant', 'Bohemian'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 12000,
    price_max: 20000,
    unit: 'package',
  },
  // Ndola / Kitwe — deliberately cheaper than their Lusaka category peers, so
  // a Lusaka-based couple can test the "further away but fits your budget
  // better" alternate-recommendation path against the "near you" primary pick.
  {
    email: 'events@minershallvenue.test',
    business_name: "Miner's Hall Venue",
    category: 'Venue',
    description: 'Historic Copperbelt hall with in-house catering partners, budget-friendly rates.',
    style_tags: ['Traditional', 'Rustic'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 5000,
    price_max: 10000,
    unit: 'package',
  },
  {
    email: 'hello@ndolahometable.test',
    business_name: 'Ndola Home Table Catering',
    category: 'Catering',
    description: 'Family-style Zambian catering for up to 150 guests, budget packages available.',
    style_tags: ['Traditional'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 3500,
    price_max: 7000,
    unit: 'per event',
  },
  {
    email: 'book@kitwegardenhall.test',
    business_name: 'Kitwe Garden Hall',
    category: 'Venue',
    description: 'Outdoor garden hall on the Copperbelt with flexible, affordable packages.',
    style_tags: ['Rustic', 'Minimalist'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 6000,
    price_max: 12000,
    unit: 'package',
  },
  {
    email: 'studio@kitweframeworks.test',
    business_name: 'Kitwe Frame Works',
    category: 'Photography',
    description: 'Budget-friendly wedding photography with a digital gallery, based in Kitwe.',
    style_tags: ['Modern', 'Minimalist'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 2000,
    price_max: 4500,
    unit: 'package',
  },

  // ── Top-up to 5 vendors per category, spread across Lusaka/Ndola/Kitwe ────

  // Catering (already has 3 above) — +2
  {
    email: 'hello@copperbeltfeast.test',
    business_name: 'Copperbelt Feast Catering',
    category: 'Catering',
    description: 'Buffet-style Zambian catering for weddings up to 250 guests, based in Kitwe.',
    style_tags: ['Traditional'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 4000,
    price_max: 8000,
    unit: 'per event',
  },
  {
    email: 'info@ndolaelegantEats.test',
    business_name: 'Ndola Elegant Eats',
    category: 'Catering',
    description: 'Plated fine-dining catering service for upscale weddings in Ndola.',
    style_tags: ['Elegant', 'Modern'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 15000,
    price_max: 28000,
    unit: 'per event',
  },

  // Photography (already has 3 above) — +2
  {
    email: 'hello@copperbeltcaptures.test',
    business_name: 'Copperbelt Captures',
    category: 'Photography',
    description: 'Full-day wedding photography with traditional and candid coverage, Kitwe-based.',
    style_tags: ['Modern', 'Traditional'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 5000,
    price_max: 9000,
    unit: 'package',
  },
  {
    email: 'book@ndolamoments.test',
    business_name: 'Ndola Moments Photography',
    category: 'Photography',
    description: 'Documentary-style wedding photography with natural light portraits.',
    style_tags: ['Bohemian', 'Minimalist'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 4000,
    price_max: 8000,
    unit: 'package',
  },

  // Decor & flowers — 5 new
  {
    email: 'hello@bloomandblossom.test',
    business_name: 'Bloom & Blossom Decor',
    category: 'Decor & flowers',
    description: 'Full-service event styling and floral design for upscale weddings.',
    style_tags: ['Elegant', 'Modern'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 6000,
    price_max: 15000,
    unit: 'package',
  },
  {
    email: 'orders@petallane.test',
    business_name: 'Petal Lane Florists',
    category: 'Decor & flowers',
    description: 'Fresh floral arrangements and simple venue styling at accessible rates.',
    style_tags: ['Rustic', 'Bohemian'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 2500,
    price_max: 6000,
    unit: 'package',
  },
  {
    email: 'studio@copperbeltbloom.test',
    business_name: 'Copperbelt Bloom Studio',
    category: 'Decor & flowers',
    description: 'Budget-friendly décor and floral hire for Copperbelt weddings.',
    style_tags: ['Rustic', 'Minimalist'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 3000,
    price_max: 7000,
    unit: 'package',
  },
  {
    email: 'hello@kitwefloraldesigns.test',
    business_name: 'Kitwe Floral Designs',
    category: 'Decor & flowers',
    description: 'Premium floral installations and full venue transformation packages.',
    style_tags: ['Elegant', 'Traditional'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 8000,
    price_max: 18000,
    unit: 'package',
  },
  {
    email: 'hello@ndolagardendecor.test',
    business_name: 'Ndola Garden Décor',
    category: 'Decor & flowers',
    description: 'Simple, elegant garden-style decor packages for outdoor weddings.',
    style_tags: ['Bohemian'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 2000,
    price_max: 5000,
    unit: 'package',
  },

  // DJ & MC — 5 new
  {
    email: 'book@amplifysounddj.test',
    business_name: 'Amplify Sound & DJ',
    category: 'DJ & MC',
    description: 'Modern sound system and DJ set for receptions up to 400 guests.',
    style_tags: ['Modern'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 4000,
    price_max: 9000,
    unit: 'package',
  },
  {
    email: 'mc@chandalive.test',
    business_name: 'MC Chanda Live Entertainment',
    category: 'DJ & MC',
    description: 'Bilingual wedding MC and traditional ceremony hosting.',
    style_tags: ['Traditional'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 2000,
    price_max: 5000,
    unit: 'package',
  },
  {
    email: 'book@copperbeltbeats.test',
    business_name: 'Copperbelt Beats DJ Crew',
    category: 'DJ & MC',
    description: 'Affordable DJ and sound hire for Copperbelt receptions.',
    style_tags: ['Modern', 'Minimalist'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 1800,
    price_max: 4000,
    unit: 'package',
  },
  {
    email: 'hello@kitwepartysounds.test',
    business_name: 'Kitwe Party Sounds',
    category: 'DJ & MC',
    description: 'Full production DJ, lighting, and MC package for larger weddings.',
    style_tags: ['Elegant'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 5000,
    price_max: 10000,
    unit: 'package',
  },
  {
    email: 'book@ndolavibe.test',
    business_name: 'Ndola Vibe Entertainment',
    category: 'DJ & MC',
    description: 'Budget DJ and MC hire with a mix of traditional and modern playlists.',
    style_tags: ['Traditional', 'Rustic'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 1500,
    price_max: 3500,
    unit: 'package',
  },

  // Transport — 4 new (there's already one Kitwe entry added by the couple manually)
  {
    email: 'book@royalridecars.test',
    business_name: 'Royal Ride Wedding Cars',
    category: 'Transport',
    description: 'Chauffeured luxury car hire for the wedding party.',
    style_tags: ['Elegant'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 3000,
    price_max: 8000,
    unit: 'per event',
  },
  {
    email: 'hello@budgetwheels.test',
    business_name: 'Budget Wheels Transport',
    category: 'Transport',
    description: 'Affordable guest shuttle and bridal car hire.',
    style_tags: ['Minimalist'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 800,
    price_max: 2000,
    unit: 'per event',
  },
  {
    email: 'book@copperbeltclassiccars.test',
    business_name: 'Copperbelt Classic Cars',
    category: 'Transport',
    description: 'Vintage and classic car hire for the wedding convoy.',
    style_tags: ['Elegant', 'Traditional'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 4000,
    price_max: 9000,
    unit: 'per event',
  },
  {
    email: 'hello@ndolashuttle.test',
    business_name: 'Ndola Shuttle & Limo',
    category: 'Transport',
    description: 'Guest shuttle service and a limo option for the couple.',
    style_tags: ['Modern'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 1200,
    price_max: 3000,
    unit: 'per event',
  },

  // Wedding attire — 5 new
  {
    email: 'hello@elegancebridal.test',
    business_name: 'Elegance Bridal House',
    category: 'Wedding attire',
    description: 'Designer bridal gowns and groom suits, made-to-measure or rental.',
    style_tags: ['Elegant'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 8000,
    price_max: 20000,
    unit: 'package',
  },
  {
    email: 'hello@chicthreads.test',
    business_name: 'Chic Threads Bridal & Suits',
    category: 'Wedding attire',
    description: 'Modern, minimalist bridal wear and suiting at mid-range prices.',
    style_tags: ['Modern', 'Minimalist'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 2500,
    price_max: 7000,
    unit: 'package',
  },
  {
    email: 'hello@copperbeltcouture.test',
    business_name: 'Copperbelt Couture',
    category: 'Wedding attire',
    description: 'Traditional and Western bridal wear, tailored locally in Kitwe.',
    style_tags: ['Traditional', 'Elegant'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 4000,
    price_max: 10000,
    unit: 'package',
  },
  {
    email: 'hello@kitwebridal.test',
    business_name: 'Kitwe Bridal Boutique',
    category: 'Wedding attire',
    description: 'Budget bridal gown rentals with free alterations.',
    style_tags: ['Bohemian'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 1500,
    price_max: 4000,
    unit: 'package',
  },
  {
    email: 'hello@ndolatailors.test',
    business_name: 'Ndola Tailors & Bridal',
    category: 'Wedding attire',
    description: 'Custom-tailored traditional wedding outfits at affordable rates.',
    style_tags: ['Traditional'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 1000,
    price_max: 3000,
    unit: 'package',
  },

  // Cake & sweets — 5 new
  {
    email: 'orders@sweetsymphony.test',
    business_name: 'Sweet Symphony Cakes',
    category: 'Cake & sweets',
    description: 'Custom multi-tier wedding cakes with elegant modern designs.',
    style_tags: ['Elegant', 'Modern'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 2500,
    price_max: 6000,
    unit: 'package',
  },
  {
    email: 'orders@sugarandspice.test',
    business_name: 'Sugar & Spice Bakery',
    category: 'Cake & sweets',
    description: 'Home-style wedding cakes and dessert tables at affordable rates.',
    style_tags: ['Rustic'],
    location: 'Lusaka',
    latitude: -15.4167,
    longitude: 28.2833,
    price_min: 900,
    price_max: 2200,
    unit: 'package',
  },
  {
    email: 'hello@copperbeltcakestudio.test',
    business_name: 'Copperbelt Cake Studio',
    category: 'Cake & sweets',
    description: 'Custom cake designs and dessert tables, based in Kitwe.',
    style_tags: ['Modern'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 1500,
    price_max: 3500,
    unit: 'package',
  },
  {
    email: 'hello@kitwesweettreats.test',
    business_name: 'Kitwe Sweet Treats',
    category: 'Cake & sweets',
    description: 'Budget wedding cakes and traditional sweets platters.',
    style_tags: ['Traditional'],
    location: 'Kitwe',
    latitude: -12.8024,
    longitude: 28.2132,
    price_min: 800,
    price_max: 1800,
    unit: 'package',
  },
  {
    email: 'hello@ndoladelight.test',
    business_name: 'Ndola Delight Bakery',
    category: 'Cake & sweets',
    description: 'Affordable wedding cakes and dessert bars for Ndola weddings.',
    style_tags: ['Rustic', 'Bohemian'],
    location: 'Ndola',
    latitude: -12.9587,
    longitude: 28.6366,
    price_min: 700,
    price_max: 1600,
    unit: 'package',
  },
];

async function main() {
  await sequelize.authenticate();
  const password_hash = await bcrypt.hash(TEST_PASSWORD, 10);

  for (const v of VENDORS) {
    const existingUser = await User.findOne({ where: { email: v.email } });
    if (existingUser) {
      console.log(`Skipping ${v.business_name} — ${v.email} already exists.`);
      continue;
    }

    const user = await User.create({
      email: v.email,
      password_hash,
      name: v.business_name,
      role: 'vendor',
      is_verified: true,
    });

    const vendor = await Vendor.create({
      user_id: user.user_id,
      business_name: v.business_name,
      description: v.description,
      category: v.category,
      location: v.location,
      latitude: v.latitude,
      longitude: v.longitude,
      tier: 'free',
      verification_status: 'verified',
      style_tags: v.style_tags,
    });

    await VendorService.create({
      vendor_id: vendor.vendor_id,
      title: `${v.category} package`,
      description: v.description,
      price_min: v.price_min,
      price_max: v.price_max,
      unit: v.unit,
    });

    console.log(`Created ${v.business_name} (${v.category}, ${v.price_min}-${v.price_max} ZMW) — login: ${v.email} / ${TEST_PASSWORD}`);
  }

  console.log('Done.');
  process.exit(0);
}

main().catch((err) => {
  console.error('Failed to seed test vendors:', err.message);
  process.exit(1);
});
